"""initial schema phases 1-5

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-10 21:17:50.269202
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_request_logs',
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=60), nullable=True),
    sa.Column('retrieved_records', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('execution_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_request_logs_conversation_id'), 'ai_request_logs', ['conversation_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATION', 'MODIFICATION', 'SUPPRESSION', 'IMPORT', name='audit_action'), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('conversations',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name_fr', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('CODE_DES_DOUANES', 'NOMENCLATURE', 'PRODUITS_CHIMIQUES', 'ENGRAIS', 'MACHINES', 'MATIERES_PLASTIQUES', 'PRODUITS_CONTROLES', 'CIRCULAIRES', 'ANNEXES', 'AUTRE', name='document_category'), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('number_of_pages', sa.Integer(), nullable=False),
    sa.Column('processed_pages', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('EN_ATTENTE', 'EN_TRAITEMENT', 'TERMINE', 'PARTIEL', 'ERREUR', 'DOUBLON', name='document_status'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_table('hs_codes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description_fr', sa.Text(), nullable=False),
    sa.Column('chapter', sa.String(length=120), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hs_codes_code'), 'hs_codes', ['code'], unique=True)
    op.create_table('invoices',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('RECUE', 'EN_TRAITEMENT', 'ANALYSEE', 'ERREUR', name='invoice_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorizations',
    sa.Column('hs_code_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REQUISE', 'NON_REQUISE', 'CONDITIONNELLE', name='authorization_status'), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('ministry', sa.String(length=200), nullable=True),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legal_reference', sa.String(length=300), nullable=True),
    sa.Column('processing_time_days', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorizations_hs_code_id'), 'authorizations', ['hs_code_id'], unique=False)
    op.create_table('hs_references',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('hs_code', sa.String(length=30), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.String(length=120), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hs_references_document_id'), 'hs_references', ['document_id'], unique=False)
    op.create_index(op.f('ix_hs_references_hs_code'), 'hs_references', ['hs_code'], unique=False)
    op.create_table('import_history',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('EN_COURS', 'REUSSI', 'PARTIEL', 'ECHOUE', 'INTERROMPU', name='import_status'), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_history_document_id'), 'import_history', ['document_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_country_id'), 'suppliers', ['country_id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('taxes',
    sa.Column('hs_code_id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('import_duty', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('vat', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('parafiscal_tax', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('additional_taxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes_fr', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxes_country_id'), 'taxes', ['country_id'], unique=False)
    op.create_index(op.f('ix_taxes_effective_date'), 'taxes', ['effective_date'], unique=False)
    op.create_index(op.f('ix_taxes_hs_code_id'), 'taxes', ['hs_code_id'], unique=False)
    op.create_table('text_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.String(length=120), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_chunks_chapter'), 'text_chunks', ['chapter'], unique=False)
    op.create_index(op.f('ix_text_chunks_document_id'), 'text_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_text_chunks_page'), 'text_chunks', ['page'], unique=False)
    op.create_table('import_analyses',
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('supplier_name_raw', sa.String(length=300), nullable=True),
    sa.Column('invoice_number', sa.String(length=120), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('incoterm', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('EN_ATTENTE', 'EN_COURS', 'TERMINE', 'PARTIEL', 'ERREUR', name='analysis_status'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('ocr_provider', sa.String(length=60), nullable=True),
    sa.Column('execution_ms', sa.Integer(), nullable=True),
    sa.Column('ai_calls', sa.Integer(), nullable=False),
    sa.Column('overall_risk', sa.Enum('FAIBLE', 'MOYEN', 'ELEVE', name='risk_level'), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_analyses_invoice_id'), 'import_analyses', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_import_analyses_status'), 'import_analyses', ['status'], unique=False)
    op.create_table('products',
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('country_of_origin_id', sa.UUID(), nullable=True),
    sa.Column('preferred_supplier_id', sa.UUID(), nullable=True),
    sa.Column('hs_code_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIF', 'INACTIF', 'ARCHIVE', name='product_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_of_origin_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_country_of_origin_id'), 'products', ['country_of_origin_id'], unique=False)
    op.create_index(op.f('ix_products_hs_code_id'), 'products', ['hs_code_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_preferred_supplier_id'), 'products', ['preferred_supplier_id'], unique=False)
    op.create_index(op.f('ix_products_reference'), 'products', ['reference'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['import_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_analysis_id'), 'analysis_reports', ['analysis_id'], unique=True)
    op.create_table('document_references',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('paragraph', sa.Text(), nullable=True),
    sa.Column('citation', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_references_document_id'), 'document_references', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_references_product_id'), 'document_references', ['product_id'], unique=False)
    op.create_table('import_analysis_items',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_product_name', sa.String(length=500), nullable=True),
    sa.Column('raw_quantity', sa.Float(), nullable=True),
    sa.Column('raw_unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('raw_currency', sa.String(length=3), nullable=True),
    sa.Column('matched_product_id', sa.UUID(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_reason', sa.String(length=300), nullable=True),
    sa.Column('match_method', sa.Enum('NOM_EXACT', 'REFERENCE', 'ALIAS', 'MARQUE', 'FABRICANT', 'SEMANTIQUE', 'AUCUNE', name='match_method'), nullable=False),
    sa.Column('hs_code_id', sa.UUID(), nullable=True),
    sa.Column('hs_code', sa.String(length=30), nullable=True),
    sa.Column('import_duty', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('vat', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('parafiscal_tax', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('authorizations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('price_variation_percent', sa.Float(), nullable=True),
    sa.Column('price_alert_level', sa.Enum('FAIBLE', 'MOYEN', 'ELEVE', name='risk_level'), nullable=True),
    sa.Column('status', sa.Enum('RAPPROCHE', 'A_VALIDER', 'SANS_DONNEES', name='item_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['import_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_results',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['import_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_aliases',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_aliases_alias'), 'product_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_product_aliases_product_id'), 'product_aliases', ['product_id'], unique=False)
    op.create_table('purchase_history',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=120), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('incoterm', sa.String(length=10), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_history_country_id'), 'purchase_history', ['country_id'], unique=False)
    op.create_index(op.f('ix_purchase_history_product_id'), 'purchase_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_history_purchased_at'), 'purchase_history', ['purchased_at'], unique=False)
    op.create_index(op.f('ix_purchase_history_supplier_id'), 'purchase_history', ['supplier_id'], unique=False)
    op.create_table('compliance_findings',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('CODE_SH_MANQUANT', 'AUTORISATION_MANQUANTE', 'PRODUIT_ABSENT', 'FOURNISSEUR_ABSENT', 'PRODUIT_RESTREINT', 'DONNEES_INCOMPLETES', 'REGLEMENTATION_EXPIREE', 'ALERTE_PRIX', name='finding_type'), nullable=False),
    sa.Column('risk', sa.Enum('FAIBLE', 'MOYEN', 'ELEVE', name='risk_level'), nullable=False),
    sa.Column('message', sa.String(length=700), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['import_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['import_analysis_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_alerts',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('FAIBLE', 'MOYEN', 'ELEVE', name='risk_level'), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('variation_percent', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['import_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['import_analysis_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_candidates',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('raw_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=True),
    sa.Column('suggested_reference', sa.String(length=120), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('A_VALIDER', 'VALIDE', 'REJETE', name='candidate_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['import_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['import_analysis_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_candidates_status'), 'product_candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_candidates_status'), table_name='product_candidates')
    op.drop_table('product_candidates')
    op.drop_table('price_alerts')
    op.drop_table('compliance_findings')
    op.drop_index(op.f('ix_purchase_history_supplier_id'), table_name='purchase_history')
    op.drop_index(op.f('ix_purchase_history_purchased_at'), table_name='purchase_history')
    op.drop_index(op.f('ix_purchase_history_product_id'), table_name='purchase_history')
    op.drop_index(op.f('ix_purchase_history_country_id'), table_name='purchase_history')
    op.drop_table('purchase_history')
    op.drop_index(op.f('ix_product_aliases_product_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_alias'), table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_table('ocr_results')
    op.drop_table('import_analysis_items')
    op.drop_index(op.f('ix_document_references_product_id'), table_name='document_references')
    op.drop_index(op.f('ix_document_references_document_id'), table_name='document_references')
    op.drop_table('document_references')
    op.drop_index(op.f('ix_analysis_reports_analysis_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_reference'), table_name='products')
    op.drop_index(op.f('ix_products_preferred_supplier_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_hs_code_id'), table_name='products')
    op.drop_index(op.f('ix_products_country_of_origin_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_import_analyses_status'), table_name='import_analyses')
    op.drop_index(op.f('ix_import_analyses_invoice_id'), table_name='import_analyses')
    op.drop_table('import_analyses')
    op.drop_index(op.f('ix_text_chunks_page'), table_name='text_chunks')
    op.drop_index(op.f('ix_text_chunks_document_id'), table_name='text_chunks')
    op.drop_index(op.f('ix_text_chunks_chapter'), table_name='text_chunks')
    op.drop_table('text_chunks')
    op.drop_index(op.f('ix_taxes_hs_code_id'), table_name='taxes')
    op.drop_index(op.f('ix_taxes_effective_date'), table_name='taxes')
    op.drop_index(op.f('ix_taxes_country_id'), table_name='taxes')
    op.drop_table('taxes')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_country_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_import_history_document_id'), table_name='import_history')
    op.drop_table('import_history')
    op.drop_index(op.f('ix_hs_references_hs_code'), table_name='hs_references')
    op.drop_index(op.f('ix_hs_references_document_id'), table_name='hs_references')
    op.drop_table('hs_references')
    op.drop_index(op.f('ix_authorizations_hs_code_id'), table_name='authorizations')
    op.drop_table('authorizations')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_hs_codes_code'), table_name='hs_codes')
    op.drop_table('hs_codes')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_request_logs_conversation_id'), table_name='ai_request_logs')
    op.drop_table('ai_request_logs')
    # ### end Alembic commands ###
